import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import NavBar from "@/components/NavBar";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecomece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="en">
        <body className={clsx(inter.className, "bg-slate-700")}>
          <NavBar />
          <main className=" h-screen p-16">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
